<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Orderan_model extends CI_Model
{

    public $table = 'orderan';
    public $id = 'id_order';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    function get_all_masuk()
    {
        $this->db->where('status', '0');
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get all Terkonfirmasi
    function get_all_konfirmasi()
    {
        $this->db->where('status', '1');
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get all pick_up
    function get_all_pickup()
    {
        $this->db->where('status', '2');
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get all pick_up
    function get_all_pickedup()
    {
        $this->db->where('status', '3');
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get all pick_up
    function get_all_proses()
    {
        $this->db->where('status', '4');
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get all pick_up
    function get_all_dikirim()
    {
        $this->db->where('status', '5');
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_order', $q);
    	$this->db->or_like('id_cus', $q);
    	$this->db->or_like('id_serv', $q);
    	$this->db->or_like('jum_item', $q);
    	$this->db->or_like('biaya', $q);
    	$this->db->or_like('tanggal', $q);
    	$this->db->or_like('tanggal_pick_up', $q);
    	$this->db->or_like('jam_pick_up', $q);
    	$this->db->or_like('status', $q);
    	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_order', $q);
    	$this->db->or_like('id_cus', $q);
    	$this->db->or_like('id_serv', $q);
    	$this->db->or_like('jum_item', $q);
    	$this->db->or_like('biaya', $q);
    	$this->db->or_like('tanggal', $q);
    	$this->db->or_like('tanggal_pick_up', $q);
    	$this->db->or_like('jam_pick_up', $q);
    	$this->db->or_like('status', $q);
    	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    function konfirmasi($id)
    {
        $sql = "UPDATE orderan SET status=1, confirmed_at=NOW() WHERE `id_order`='$id'
                ";
        $query = $this->db->query($sql);
        return $query;
    }

    function dijemput($id)
    {
        $sql = "UPDATE orderan SET status=2, pick_up_at=NOW() WHERE `id_order`='$id'
                ";
        $query = $this->db->query($sql);
        return $query;
    }

    function dibawa($id)
    {
        $sql = "UPDATE orderan SET status=3, picked_up_at=NOW() WHERE `id_order`='$id'
                ";
        $query = $this->db->query($sql);
        return $query;
    }

    function diproses($id)
    {
        $sql = "UPDATE orderan SET status=4, process_at=NOW() WHERE `id_order`='$id'
                ";
        $query = $this->db->query($sql);
        return $query;
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Orderan_model.php */
/* Location: ./application/models/Orderan_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-07-03 12:43:32 */
/* http://harviacode.com */